baseURL = 'http://www.bajproductions.com/'
languageCode = 'en-us'
title = 'BAJ Productions'

# no mount necessary, Hugo assumes it is a theme
[[module.imports]]
path="github.com/coonce/hugo-bootstrap5"
disabled=false
